// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD03Osicb6anw2Onrb6App2KMcsWGQTQ3g',
    appId: '1:594766816357:web:fd5443d60711099046d28c',
    messagingSenderId: '594766816357',
    projectId: 'memo-snap-eb3aa',
    authDomain: 'memo-snap-eb3aa.firebaseapp.com',
    storageBucket: 'memo-snap-eb3aa.appspot.com',
    measurementId: 'G-H7CFV1GFYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa-4MrNNCTnvocIMxn2XcHEJOQLSSm3mE',
    appId: '1:594766816357:android:3229cf82bdf0fa0a46d28c',
    messagingSenderId: '594766816357',
    projectId: 'memo-snap-eb3aa',
    storageBucket: 'memo-snap-eb3aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC6Z64_jl23h654LNpsM0Oe3hPonzyCZo',
    appId: '1:594766816357:ios:b3dde2de4b97ee0b46d28c',
    messagingSenderId: '594766816357',
    projectId: 'memo-snap-eb3aa',
    storageBucket: 'memo-snap-eb3aa.appspot.com',
    iosBundleId: 'com.example.memoSnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC6Z64_jl23h654LNpsM0Oe3hPonzyCZo',
    appId: '1:594766816357:ios:b3dde2de4b97ee0b46d28c',
    messagingSenderId: '594766816357',
    projectId: 'memo-snap-eb3aa',
    storageBucket: 'memo-snap-eb3aa.appspot.com',
    iosBundleId: 'com.example.memoSnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD03Osicb6anw2Onrb6App2KMcsWGQTQ3g',
    appId: '1:594766816357:web:448023039b7a3d0f46d28c',
    messagingSenderId: '594766816357',
    projectId: 'memo-snap-eb3aa',
    authDomain: 'memo-snap-eb3aa.firebaseapp.com',
    storageBucket: 'memo-snap-eb3aa.appspot.com',
    measurementId: 'G-45SL2MQCRL',
  );
}
